version: '3.8'

services:
  cli:
    build:
      context: .
      target: base
    networks:
      - postgres
    volumes:
      - ./src/:/app/src
      - ./bin/:/app/bin
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: ${PG_DB:-solaf}
      PG_USER: ${PG_USER:-solaf} # yes, publishing creds (even dev's) bad practice,
      PG_PASS: ${PG_PASS:-solaf} # but without k8s start CMD line will be so long
      MQ_HOST: rabbit
      MQ_USER: ${MQ_USER:-solaf}
      MQ_PASS: ${MQ_PASS:-solaf}
    depends_on:
      postgres:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      image-loader:
        condition: service_started

  image-loader:
    build:
      context: .
      target: image-loader
    networks:
      - postgres
    volumes:
      - ./src/:/app/src
      - ./bin/:/app/bin
      - ./storage/:/app/storage
    environment:
      MQ_HOST: rabbit
      MQ_USER: ${MQ_USER:-solaf}
      MQ_PASS: ${MQ_PASS:-solaf}
      APP_STORAGE: "/app/storage"
    depends_on:
      rabbit:
        condition: service_healthy

  postgres:
    hostname: postgres
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${PG_DB:-solaf}
      POSTGRES_USER: ${PG_USER:-solaf}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-solaf}
      PGDATA: /data/postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - "8432:5432"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: pg_isready
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2s

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

  rabbit:
    container_name: container_rabbit
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER:-solaf}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASS:-solaf}
    volumes:
      - ./.data/rabbitmq/:/var/lib/rabbitmq
    networks:
      - postgres
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 3s

networks:
  postgres:
    driver: bridge